CREATE TABLE IF NOT EXISTS customers (id INT, first_name VARCHAR(50), last_name VARCHAR(50),city VARCHAR(50),state VARCHAR(50));
insert into customers (id, first_name, last_name, city, state) values (1, 'Steven', 'Ewen', 'Phoenix', 'AZ');
insert into customers (id, first_name, last_name, city, state) values (2, 'Barclay', 'Frodsham', 'Philadelphia', 'PA');
insert into customers (id, first_name, last_name, city, state) values (3, 'Jedediah', 'Kornacki', 'Saint Louis', 'MO');
insert into customers (id, first_name, last_name, city, state) values (4, 'Il\'\'yse', 'McClinton', 'Dallas', 'TX');
insert into customers (id, first_name, last_name, city, state) values (5, 'Leandra', 'Waylett', 'New York City', 'NY');
insert into customers (id, first_name, last_name, city, state) values (6, 'Bren!', 'Deval', 'Huntington', 'WV');
insert into customers (id, first_name, last_name, city, state) values (7, 'Barthel', 'Si"lson', 'Yakima', 'WA');
insert into customers (id, first_name, last_name, city, state) values (8, 'Lorri', 'Ivashov', 'San Francisco', 'CA');
insert into customers (id, first_name, last_name, city, state) values (9, 'Kyle', 'Smith', 'Baton Rouge', 'LA');
insert into customers (id, first_name, last_name, city, state) values (10, 'Klarrisa', 'Mans\'er', 'New Orleans', 'LA');
insert into customers (id, first_name, last_name, city, state) values (11, 'Aeriel', 'Abelov', 'Honolulu', 'HI');
insert into customers (id, first_name, last_name, city, state) values (12, 'Alis', 'Domenicone', 'Pasadena', 'CA');
insert into customers (id, first_name, last_name, city, state) values (13, 'Sosanna', 'Le Cornu', 'Tacoma', 'WA');
insert into customers (id, first_name, last_name, city, state) values (14, 'Sosanna', 'Mordacai', 'Terre Haute', 'IN');
insert into customers (id, first_name, last_name, city, state) values (15, 'Lyndel', 'Merrisson', 'Montgomery', 'AL');
insert into customers (id, first_name, last_name, city, state) values (16, 'Toby', 'Leslie', 'Austin', 'TX');
insert into customers (id, first_name, last_name, city, state) values (17, 'Madalyn', 'Guiducci', 'Topeka', 'KS');
insert into customers (id, first_name, last_name, city, state) values (18, 'Aloysius', 'Lapere', 'Tacoma', 'WA');
insert into customers (id, first_name, last_name, city, state) values (19, 'Barthel', 'Sil$on', 'Yakima', 'WA');
insert into customers (id, first_name, last_name, city, state) values (20, 'Thaxter', 'Lippingwell', 'Cedar Rapids', 'IA');
insert into customers (id, first_name, last_name, city, state) values (21, 'Adrianna', 'Derks', 'Memphis', 'TN');
insert into customers (id, first_name, last_name, city, state) values (22, 'Alicia', 'Dike', 'Phoenix', 'AZ');
insert into customers (id, first_name, last_name, city, state) values (23, 'Ewen', 'Dike', 'Phoenix', 'AZ');
insert into customers (id, first_name, last_name, city, state) values (24, 'Steve', 'Ivashov', 'San Francisco', 'CA');
insert into customers (id, first_name, last_name, city, state) values (25, 'Ky1e', 'Bonehill', 'Baton Rouge', 'LA');
